version: "3.9"

services:
  mintlify:
    build: .
    container_name: mintlify-docs
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
